### ISSUE TITLE
Add Height of Binary Search Tree in Java

### ISSUE THREAD

**Issue by Abdulkadir98** [fnplus/Algorithms-Hacktoberfest#170]

**Comment by xlogix** [comment]
Thank you for contributing! There seems to be a problem with the name of the file. The extension is "jsvs" instead of "java".

**Comment by Abdulkadir98** [comment]
Hi I've made a new pull request https://github.com/fnplus/Algorithms-Hacktoberfest/pull/174

**Comment by xlogix** [comment]
Great!
